### ISSUE TITLE
Scan Numbers in Summary Plot

### ISSUE THREAD

**Issue by znarthur** [Beamlines-CanadianLightSource/SGM_Nexpy#3]
The scan numbers in the summary plot graph generated by xas_multi are indexed from 1 and not necessarily to the scan entry number.   This can be confusing for users, as they would have to add the first entry offset to the index of the summary plot to determine the entry number in bad scans.

**Comment by Henry0422** [comment]
Now, I am working on this. :sunglasses::sunglasses:

**Comment by Henry0422** [comment]
Already fixed this issue. No matter how the order of scans are constructed in the list, the summary plot function will show the real entry number on the diagram. For more information, please check: https://github.com/Beamlines-CanadianLightSource/SGM_Nexpy/commit/90494d7068e518e4a2fe76b291abe1309390109c
